# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 「更新京喜工厂开团ID」

on:
  workflow_dispatch:
  repository_dispatch:
    types: jd_updateFactoryTuanID
jobs:
  build:

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: '运行 「更新京喜工厂开团ID」'
        run: |
          node jd_jxFactoryCreateTuan.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
